Airport/Models/Airplane.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Airport.Models
{
    public class Airplane
    {
        public Airplane()
        {
        }

        [Key]
        public Guid AirplaneID { get; set; }

        [Required]
        [StringLength(20)]
        [Display(Name = "Airplane Type")]
        public string AirplaneType { get; set; }

        [Required]
        [Range(0, 200)]
        [Display(Name = "Number of places")]
        public string NumPlaces { get; set; }

        public Guid AirlineID { get; set; }
        public Airline Airline { get; set; }
    }
}

Airport/Controllers/AirplaneController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Airport.Data;
using Airport.Models;
using Microsoft.AspNetCore.Mvc;

namespace Airport.Controllers
{
    public class AirplaneController : Controller
    {
        private readonly ApplicationDbContext _DBcontext;

        public AirplaneController(ApplicationDbContext context)
        {
            _DBcontext = context;
        }

        public IActionResult Index()
        {
            IList<Airplane> airplanes = _DBcontext.Airplanes.ToList();
            return View(airplanes);
        }

        public IActionResult Add(Guid id)
        {
            if(id != null)
            {
                ViewBag.Airlines = _DBcontext.Airlines.ToList();
                return View(_DBcontext.Airlines.Where(x => x.AirlineID.Equals(id)).FirstOrDefault());
            }
            else
            {
                Airplane airplane = new Airplane();
                ViewBag.Airlines = _DBcontext.Airlines.ToList();
                return View(airplane);
            }            
        }
    }
}

Airport/Controllers/Api/AirplaneController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Airport.Data;
using Airport.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Airport.Controllers.Api
{
    [Produces("application/json")]
    [Route("api/Airplane")]
    public class AirplaneController : Controller
    {

        private readonly ApplicationDbContext _context;

        public AirplaneController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: api/Airplane
        [HttpGet]
        public IActionResult GetAirplane()
        {
            foreach(Airplane a in _context.Airplanes.ToList()) {
                a.Airline = _context.Airlines.FirstOrDefault(x => x.AirlineID.Equals(a.AirlineID));
            }
            return Json(new { data =  _context.Airplanes.ToList()});
        }


        // POST: api/Airplane
        [HttpPost]
        public async Task<IActionResult> PostAirplane([FromBody] Airplane air)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            try
            {
                Airplane airplane = new Airplane();
                airplane.AirlineID = air.AirlineID;
                airplane.AirplaneType = air.AirplaneType;
                airplane.NumPlaces = air.NumPlaces;

                if (air.AirplaneID == Guid.Empty)
                {
                    airplane.AirplaneID = Guid.NewGuid();
                    _context.Airplanes.Add(airplane);

                     await _context.SaveChangesAsync();

                    return Json(new { success = true, message = "Add new data success." });
                }
                else
                {
                    airplane.AirplaneID = air.AirplaneID;
                    _context.Update(airplane);

                    int i = await _context.SaveChangesAsync();

                    return Json(new { success = true, message = "Edit data success." });
                }
            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = ex.Message });
            }

         }

        // DELETE: api/Airplane/....
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteAirplane([FromRoute] Guid id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            try
            {
                var airplane = _context.Airplanes.SingleOrDefault(m => m.AirplaneID == id);
                if (airplane == null)
                {
                    return NotFound();
                }

                _context.Airplanes.Remove(airplane);
                await _context.SaveChangesAsync();

                return Json(new { success = true, message = "Delete success." });
            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = ex.Message });
            }


        }

        private Airplane AirplaneExists(Guid id)
        {
            return _context.Airplanes.Where(e => e.AirplaneID == id).SingleOrDefault();
        }
    }
}

Airport/Views/Airplane/Add.cshtml
@model Airport.Models.AirplaneViewModels.AddAirplaneViewModel
@{
    Layout = null;
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Add or Edit Data</h4>
</div>
<form onsubmit="return SubmitAddEdit(this)" id="form">
    <div class="box-body">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input asp-for="@Model.AirplaneID" type="hidden" />
        <div class="form-group">
            <label asp-for="@Model.AirplaneType" class="control-label"></label>
            <input asp-for="@Model.AirplaneType" class="form-control" />
            <span asp-validation-for="@Model.AirplaneType" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.NumPlaces" class="control-label"></label>
            <input asp-for="@Model.NumPlaces" class="form-control" id="numplaces" />
            <span asp-validation-for="@Model.NumPlaces"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.AirlineID" class="control-label"></label>
            <input asp-for="@Model.AirlineID" type="hidden" id="airlineid" />
            <select asp-for="@Model.AirlineID" class="form-control select2 select2-hidden-accessible">
                @foreach (var airline in ViewBag.Airlines)
                {
                    <option value="@airline.AirlineID">@airline.AirlineFullName</option>
                }
            </select>
        </div>
    </div>

    <div class="box-footer">
        <button type="submit" class="btn btn-primary pull-right"><i class="fa fa-save"></i> Submit</button>
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</button>
    </div>
</form>

<script>
    Ladda.bind('.btn', { timeout: 1000 });
</script>

Airport/Views/Airplane/AddEdit.cshtml
@model Airport.Models.Airplane
@{
    Layout = null;
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Add or Edit Data</h4>
</div>
<form onsubmit="return SubmitAddEdit(this)" id="form">
    <div class="box-body">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input asp-for="AirplaneID" type="hidden" />
        <div class="form-group">
            <label asp-for="AirplaneType" class="control-label"></label>
            <input asp-for="AirplaneType" class="form-control" />
            <span asp-validation-for="AirplaneType" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="NumPlaces" class="control-label"></label>
            <input asp-for="NumPlaces" class="form-control" id="numplaces" />
            <span asp-validation-for="NumPlaces"></span>
        </div>
        <div class="form-group">
            <label asp-for="AirlineID" class="control-label"></label>
            <input asp-for="AirlineID" type="hidden" id="airlineid" />
            <select asp-for="AirlineID" class="form-control select2 select2-hidden-accessible">
                @foreach (var airline in ViewBag.Airlines)
                {
                    <option value="@airline.AirlineID">@airline.AirlineFullName</option>
                }
            </select>
        </div>
    </div>

    <div class="box-footer">
        <button type="submit" class="btn btn-primary pull-right"><i class="fa fa-save"></i> Submit</button>
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</button>
    </div>
</form>

<script>
    Ladda.bind('.btn', { timeout: 1000 });
</script>

Airport/Views/Airplane/Index.cshtml
@model IEnumerable<Airport.Models.Airplane>
@{
    ViewData["Title"] = "Airlines";
    Layout = "_Layout";
}

<section class="content">
    <div class="row">
        <div class="col-lg-10">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <table id="grid" name="grid" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>AirplaneType</th>
                                        <th>NumPlaces</th>
                                        <th>Airline</th>
                                        <th></th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-lg-2">
            <div class="row">
                <div class="col-md-12">
                    <a class="btn btn-success" style="margin-bottom:10px" onclick="ShowPopup('@Url.Action("Add","Airplane")')"><i class="fa fa-plus"></i> Add New Airplane</a>
                </div>
            </div>
        </div>
    </div>

</section>

<div class="modal modal-primary fade" id="modalDefault">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
    </div>
</div>



@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial")
    <script src="~/js/views/airplane/index.js"></script>
}