Airport/Models/Ticket.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Airport.Models
{
    public class Ticket
    {

        public Ticket()
        {
        }

        [Key]
        public Guid TicketID { get; set; }

        [Required]
        public Guid FlightFligthID { get; set; }
        [ForeignKey("FlightFligthID")]
        public Flight Flight { get; set; }

        [Required]
        public Guid UserId { get; set; }
        [ForeignKey("UserId")]
        public User User { get; set; }

        [Required]
        public int Seat { get; set; }

        [Required]
        public double Price { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime OrderDate { get; set; }

    }
}

Airport/Controllers/Api/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Airport.Data;
using Airport.Models;
using Airport.Models.TicketViewModels;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Airport.Controllers.Api
{
    [Produces("application/json")]
    [Route("api/Ticket")]
    public class TicketController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TicketController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: api/Ticket
        [HttpGet]
        public IActionResult GetTickets()
        {
            List<TicketDataTableModel> tickets = new List<TicketDataTableModel>();

            foreach (Ticket t in _context.Ticket.ToList())
            {
                TicketDataTableModel model = new TicketDataTableModel();
                Flight f = _context.Flights.FirstOrDefault(x => x.FligthID.Equals(t.FlightFligthID));
                Airportt airportFrom = _context.Airportts.FirstOrDefault(x => x.AirportID.Equals(f.AirportFromAirportID));
                Airportt airportTo = _context.Airportts.FirstOrDefault(x => x.AirportID.Equals(f.AirportToAirportID));

                model.TicketID = t.TicketID;
                model.Seat = t.Seat;
                model.Price = t.Price;
                model.OrderDate = t.OrderDate;
                model.User = _context.User.FirstOrDefault(x => x.UserId.Equals(t.UserId));   
                model.AirportFrom = airportFrom.AirportName + "( " + airportFrom.CountryName + ", " + airportFrom.CityName + ")";
                model.AirportTo = airportTo.AirportName + "( " + airportTo.CountryName + ", " + airportTo.CityName + ")";
                model.DepartureDate = f.DepartureDate;

                tickets.Add(model);
            }
            return Json(new { data = tickets });
        }


        // POST: api/Ticket
        [HttpPost]
        public async Task<IActionResult> PostTicket([FromBody] Ticket ticket)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            try
            {
                ticket.Price = 2 * _context.Flights.FirstOrDefault(f => f.FligthID.Equals(ticket.FlightFligthID)).PriceFlight;
                if (ticket.TicketID == Guid.Empty)
                {
                    ticket.TicketID = Guid.NewGuid();
                    ticket.OrderDate = DateTime.Today;
                    _context.Ticket.Add(ticket);

                    await _context.SaveChangesAsync();

                    return Json(new { success = true, message = "Add new data success." });
                }
                else
                {
                    _context.Update(ticket);

                    await _context.SaveChangesAsync();

                    return Json(new { success = true, message = "Edit data success." });
                }
            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = ex.Message });
            }

        }

        // DELETE: api/Ticket/....
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteTicket([FromRoute] Guid id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            try
            {
                var ticket = _context.Ticket.SingleOrDefault(m => m.TicketID == id);
                if (ticket == null)
                {
                    return NotFound();
                }

                _context.Ticket.Remove(ticket);
                await _context.SaveChangesAsync();

                return Json(new { success = true, message = "Delete success." });
            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = ex.Message });
            }


        }

        private bool TicketExists(Guid id)
        {
            return _context.Ticket.Any(e => e.TicketID == id);
        }
    }
}

Airport/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Airport.Data;
using Airport.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Airport.Controllers
{
    public class TicketController : Controller
    {

        private readonly ApplicationDbContext _DBcontext;

        public TicketController(ApplicationDbContext context)
        {
            _DBcontext = context;
        }

        public IActionResult Index()
        {
            IList<Ticket> users = _DBcontext.Ticket.ToList();
            return View(users);
        }

        public IActionResult AddEdit(Guid id)
        {
            List<Flight> flights = _DBcontext.Flights.ToList();
            foreach (Flight fl in flights)
            {
                fl.AirportFrom = _DBcontext.Airportts.FirstOrDefault(x => x.AirportID.Equals(fl.AirportFromAirportID));
                fl.AirportTo = _DBcontext.Airportts.FirstOrDefault(x => x.AirportID.Equals(fl.AirportToAirportID));
            }
            ViewBag.Flights = flights;
            ViewBag.Users = _DBcontext.User.ToList();
            if (id != Guid.Empty)
            {             
                return View(_DBcontext.Ticket.Where(x => x.TicketID.Equals(id)).FirstOrDefault());
            }
            else
            {
                Ticket ticket = new Ticket();
                return View(ticket);
            }
        }
    }
}

Airport/Views/Ticket/AddEdit.cshtml
@model Airport.Models.Ticket
@{
    Layout = null;
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Add or Edit Data</h4>
</div>
<form onsubmit="return SubmitAddEdit(this)">
    <div class="box-body">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="TicketID" />
        <div class="form-group">
            <label asp-for="FlightFligthID" class="control-label"></label>
            <input asp-for="FlightFligthID" type="hidden" />
            <select asp-for="FlightFligthID" class="form-control select2 select2-hidden-accessible">
                @foreach (var flight in ViewBag.Flights)
                {
                    <option value="@flight.FligthID">
                        @flight.AirportFrom.AirportName (@flight.AirportFrom.CountryName, @flight.AirportFrom.CityName) -
                        @flight.AirportTo.AirportName (@flight.AirportTo.CountryName, @flight.AirportTo.CityName)
                    </option>
                }
            </select>
        </div>
        <div class="form-group">
            <label asp-for="UserId" class="control-label"></label>
            <input asp-for="UserId" type="hidden" />
            <select asp-for="UserId" class="form-control select2 select2-hidden-accessible">
                @foreach (var user in ViewBag.Users)
                {
                    <option value="@user.UserId"> @user.UserName </option>
                }
            </select>
        </div>
        <div class="form-group">
            <label asp-for="Seat" class="control-label"></label>
            <input asp-for="Seat" class="form-control" />
            <span asp-validation-for="Seat" class="text-danger"></span>
        </div>
    </div>

    <div class="box-footer">
        <button type="submit" class="btn btn-primary pull-right"><i class="fa fa-save"></i> Submit</button>
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</button>
    </div>
</form>
<script>
    Ladda.bind('.btn', { timeout: 1000 });
</script>

Airport/Views/Ticket/Index.cshtml
@model IEnumerable<Airport.Models.Ticket>
@{
    ViewData["Title"] = "Flights";
    Layout = "_Layout";
}

<section class="content">
    <div class="row">
        <div class="col-lg-10">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="row">
                        <div class="col-lg-12" >
                            <table id="grid" name="grid" class="table table-striped table-bordered" >
                                <thead>
                                    <tr>
                                        <th>Departure Date</th>
                                        <th>From</th>
                                        <th>To</th>
                                        <th>User</th>
                                        <th>Seat</th>
                                        <th>Price</th>
                                        <th>Order date</th>
                                        <th width="40px"></th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-lg-2">
            <div class="row">
                <div class="col-md-12">
                    <a class="btn btn-success" style="margin-bottom:10px" onclick="ShowPopup('@Url.Action("AddEdit","Ticket")')"><i class="fa fa-plus"></i> Add New Ticket</a>
                </div>
            </div>
        </div>
    </div>

</section>

<div class="modal modal-primary fade" id="modalDefault">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
    </div>
</div>



@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial")
    <script src="~/js/views/ticket/index.js"></script>
}