Airport/Controllers/AirportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Airport.Data;
using Airport.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Airport.Controllers
{
    public class AirportController : Controller
    {
        private readonly ApplicationDbContext _DBcontext;

        public AirportController(ApplicationDbContext context)
        {
            _DBcontext = context;
        }

        public IActionResult Index()
        {
            IList<Airportt> airports = _DBcontext.Airportts.ToList();
            return View(airports);
        }

        public IActionResult AddEdit(Guid id)
        {
            if (id == Guid.Empty)
            {
                Airportt airport = new Airportt();
                return View(airport);
            }
            else
            {
                return View(_DBcontext.Airportts.Where(x => x.AirportID.Equals(id)).FirstOrDefault());
            }

        }
    }
}

Airport/Views/Airport/AddEdit.cshtml
@model Airport.Models.Airportt
@{
    Layout = null;
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Add or Edit Data</h4>
</div>
<form onsubmit="return SubmitAddEdit(this)">
    <div class="box-body">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="AirportID" />
        <div class="form-group">
            <label asp-for="AirportName" class="control-label"></label>
            <input asp-for="AirportName" class="form-control" />
            <span asp-validation-for="AirportName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="CountryName" class="control-label"></label>
            <input asp-for="CountryName" class="form-control" />
            <span asp-validation-for="CountryName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="CityName" class="control-label"></label>
            <input asp-for="CityName" class="form-control" />
            <span asp-validation-for="CityName" class="text-danger"></span>
        </div>
    </div>

    <div class="box-footer">
        <button type="submit" class="btn btn-primary pull-right"><i class="fa fa-save"></i> Submit</button>
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</button>
    </div>
</form>
<script>
    Ladda.bind('.btn', { timeout: 1000 });
</script>

Airport/Views/Airport/Index.cshtml
@model IEnumerable<Airport.Models.Airportt>
@{
    ViewData["Title"] = "Airports";
    Layout = "_Layout";
}

<section class="content">
    <div class="row">
        <div class="col-lg-10">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <table id="grid" name="grid" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>Airport Type</th>
                                        <th>Country Name</th>
                                        <th>City Name</th>
                                        <th></th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-lg-2">
            <div class="row">
                <div class="col-md-12">
                    <a class="btn btn-success" style="margin-bottom:10px" onclick="ShowPopup('@Url.Action("AddEdit","Airport")')"><i class="fa fa-plus"></i> Add New Airport</a>
                </div>
            </div>
        </div>
    </div>

</section>

<div class="modal modal-primary fade" id="modalDefault">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
    </div>
</div>



@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial")
    <script src="~/js/views/airport/index.js"></script>
}