Airport/Controllers/Api/TimeTableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Airport.Data;
using Airport.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Airport.Controllers.Api
{
    [Produces("application/json")]
    [Route("api/TimeTable")]
    public class TimeTableController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TimeTableController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: api/TimeTable
        [HttpGet]
        public IActionResult GetTimeTables()
        {
            return Json(new { data = _context.TimeTables.ToList() });
        }


        // POST: api/TimeTable
        [HttpPost]
        public async Task<IActionResult> PostAirline([FromBody] TimeTable timeTable)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            try
            {

                if (timeTable.TimeTableID == Guid.Empty)
                {
                    timeTable.TimeTableID = Guid.NewGuid();
                    _context.TimeTables.Add(timeTable);

                    await _context.SaveChangesAsync();

                    return Json(new { success = true, message = "Add new data success." });
                }
                else
                {
                    _context.Update(timeTable);

                    await _context.SaveChangesAsync();

                    return Json(new { success = true, message = "Edit data success." });
                }
            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = ex.Message });
            }

        }

        // DELETE: api/TimeTable/....
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteTimeTable([FromRoute] Guid id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            try
            {
                var timeTable = _context.TimeTables.SingleOrDefault(m => m.TimeTableID == id);
                if (timeTable == null)
                {
                    return NotFound();
                }

                _context.TimeTables.Remove(timeTable);
                await _context.SaveChangesAsync();

                return Json(new { success = true, message = "Delete success." });
            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = ex.Message });
            }


        }

        private bool TimeTableExists(Guid id)
        {
            return _context.TimeTables.Any(e => e.TimeTableID == id);
        }
    }
}

Airport/Controllers/TimeTableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Airport.Data;
using Airport.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Airport.Controllers
{
    public class TimeTableController : Controller
    {
        private readonly ApplicationDbContext _DBcontext;

        public TimeTableController(ApplicationDbContext context)
        {
            _DBcontext = context;
        }

        public IActionResult Index()
        {
            IList<TimeTable> timetables = _DBcontext.TimeTables.ToList();
            return View(timetables);
        }

        public IActionResult AddEdit(Guid id)
        {
            if (id == Guid.Empty)
            {
                TimeTable timeTable = new TimeTable();
                return View(timeTable);
            }
            else
            {
                return View(_DBcontext.TimeTables.Where(x => x.TimeTableID.Equals(id)).FirstOrDefault());
            }

        }
    }
}

Airport/Views/TimeTable/AddEdit.cshtml
@model Airport.Models.TimeTable
@{
    Layout = null;
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Add or Edit Data</h4>
</div>
<form onsubmit="return SubmitAddEdit(this)">
    <div class="box-body">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="TimeTableID" />
        <div class="form-group">
            <label asp-for="FlightTime" class="control-label"></label>
            <input asp-for="FlightTime" class="form-control" />
            <span asp-validation-for="FlightTime" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="MondayTimeTable" class="control-label"></label>
            <input asp-for="MondayTimeTable" class="form-control" />
            <span asp-validation-for="MondayTimeTable" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="TuesdayTimeTable" class="control-label"></label>
            <input asp-for="TuesdayTimeTable" class="form-control" />
            <span asp-validation-for="TuesdayTimeTable" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="WednesdayTimeTable" class="control-label"></label>
            <input asp-for="WednesdayTimeTable" class="form-control" />
            <span asp-validation-for="WednesdayTimeTable" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ThursdayTimeTable" class="control-label"></label>
            <input asp-for="ThursdayTimeTable" class="form-control" />
            <span asp-validation-for="ThursdayTimeTable" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="FridayTimeTable" class="control-label"></label>
            <input asp-for="FridayTimeTable" class="form-control" />
            <span asp-validation-for="FridayTimeTable" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="SundayTimeTable" class="control-label"></label>
            <input asp-for="SundayTimeTable" class="form-control" />
            <span asp-validation-for="SundayTimeTable" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="SaturdayTimeTable" class="control-label"></label>
            <input asp-for="SaturdayTimeTable" class="form-control" />
            <span asp-validation-for="SaturdayTimeTable" class="text-danger"></span>
        </div>
    </div>

    <div class="box-footer">
        <button type="submit" class="btn btn-primary pull-right"><i class="fa fa-save"></i> Submit</button>
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</button>
    </div>
</form>
<script>
    Ladda.bind('.btn', { timeout: 1000 });
</script>

Airport/Views/TimeTable/Index.cshtml
@model IEnumerable<Airport.Models.TimeTable>
@{
    ViewData["Title"] = "TimeTables";
    Layout = "_Layout";
}

<section class="content">
    <div class="row">
        <div class="col-lg-10">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <table id="grid" name="grid" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>Flight Time</th>
                                        <th>Monday</th>
                                        <th>Tuesday</th>
                                        <th>Wednesday</th>
                                        <th>Thursday</th>
                                        <th>Friday</th>
                                        <th>Saturday</th>
                                        <th>Sunday</th>
                                        <th width="40px"></th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-lg-2">
            <div class="row">
                <div class="col-md-12">
                    <a class="btn btn-success" style="margin-bottom:10px" onclick="ShowPopup('@Url.Action("AddEdit","TimeTable")')"><i class="fa fa-plus"></i> Add New TimeTable</a>
                </div>
            </div>
        </div>
    </div>

</section>

<div class="modal modal-primary fade" id="modalDefault">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
    </div>
</div>



@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial")
    <script src="~/js/views/timetable/index.js"></script>
}